#kakao:
#  key: af2408226e91805021d1adc7a9d31b36
#  baseUrl: https://dapi.kakao.com
#  categoryUrl: /v2/local/search/category
#  keywordUrl: /v2/local/search/keyword
#  categoryGroupCode: category_group_code
#  rect: rect
#  query: query
#  maxDocumentCount: 15
#  maxPageableCount: 45